title: BambiBlog
description: Welcome to BambiBlog!
author: Bambi Sheng
avatar: /logo.jpg
email: bambisheng@outlook.com
location: Beijing

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
subscribe: false
paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpg
social:
  name: Bambi Sheng
  links:
    - https://github.com/BambiSheng
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
intensedebate_comments: true
